/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import { TextureLoader } from "three";

export function ChristmasTree() {
  const { nodes, materials } = useGLTF("/christmas_tree_presents.glb");

  // Loading tree texture
  const treeTexture = useTexture("/christmas_tree.png");
  treeTexture.flipY = false;
  return (
    <group scale={0.1} dispose={null} position={[-0.1, 0, 0]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle001.geometry}
        material={materials.Brown}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle001_1.geometry}
        // material={materials["Pine Tree"]}
      >
        <meshBasicMaterial transparent map={treeTexture} depthWrite={false} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle001_2.geometry}
        material={materials["Material.003"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle001_3.geometry}
        material={materials.Red_Metallic}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle001_4.geometry}
        material={materials.Golden_Metallic}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle001_5.geometry}
        material={materials.Black}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle001_6.geometry}
        material={materials["Light Bulb_Emission"]}
      />
      <group position={[0, -0.03, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube052.geometry}
          material={materials.Golden_Metallic}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube052_1.geometry}
          material={materials.Red}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube052_2.geometry}
          material={materials.White}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube052_3.geometry}
          material={materials.Green}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube052_4.geometry}
          material={materials.Red_Metallic}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube052_5.geometry}
          material={materials.Brown}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/christmas_tree_presents.glb");
